spring:
  application:
    name: Vize
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost/vize
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:/sql/01_schema.sql
#      data-locations: classpath:sql/03_data.sql