spring:
  application:
    name: Vize
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost/vize
  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:sql/data.sql